
services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"

# docker run --gpus=all -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
  ollama:
    build:
      context: .
      dockerfile: ollama.dockerfile
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
